ユーザーの削除機能の追加
luxiar/Gunma pull request #34
Opened 2024-06-25 00:18 UTC by maru3460

Closes #14

2024-06-25 07:40 UTC, shoynoi commented on app/views/users/_form.html.erb
> +  </div>
ユーザーを追加するときに退職済みなユーザーを追加することはないかなと思うので、新規登録時は表示しないようにしてもいいかもですね
`.persisted?` とかが使えるのかな

2024-06-25 07:40 UTC, shoynoi commented on app/views/users/index.html.erb
> +        <% if user_signed_in? %>
少し細かいですが、 `id` が header と重複しているので避けたいですね。特に指定の必要がなければ削除しておいて良いと思います
あと、ログイン済みかのチェックも特に不要かなと思います！

2024-06-25 07:40 UTC, shoynoi commented on app/models/user.rb
> +  enum :status, %i[active on_leave retired]
また、日報アプリで休職中までは管理しなくてもいいかなーと個人的には感じています。
とりあえずは在籍していることと退職済みであることがわかれば十分かと思っています！

2024-06-25 07:40 UTC, shoynoi commented on app/models/ability.rb
> +    can %i[read retired all], User
`retired` はすでに不要になっていたりしますか？

2024-06-25 08:44 UTC, maru3460 commented on db/migrate/20240625041839_delete_column_deleted_at.rb
> +  def up
覚えておきます！

2024-06-25 08:51 UTC, maru3460 commented on app/assets/stylesheets/application.scss
> +.nav-link-hover-opacity:hover {
nav-linkとは一緒に使えないみたいです💦

2024-06-26 01:41 UTC, hikarook94 requested changes
コメントしました！

2024-06-26 01:41 UTC, hikarook94 commented on app/views/users/_form.html.erb
一般ユーザーのステータスを管理者で変更しようとすると、一般ユーザーのパスワード入力が必須になっていて変更できないようになっているみたいです。
おそらくステータスは管理者側でも操作したい項目だと思うので修正が必要と思います。

2024-06-26 02:17 UTC, maru3460 commented on app/views/users/index.html.erb
> +        <% if user_signed_in? %>
いらなかったです💦

2024-06-26 03:35 UTC, shoynoi commented on app/controllers/users_controller.rb
> +    if admin_edit_other_user(@user) ? @user.update_without_password(user_params_without_password) : @user.update(user_params)
基本的にはコントローラーでhelperは呼び出せないのでエラーになっていますね
`view_context` 経由なら呼び出すことができます

`update_without_password` について、deviseから利用できるAPIをよく見ていていいですね 👍 
ただ、 `user_params_without_password` で password, password_confirmation を除いていますが、 `update_without_password` のなかで delete されるので `user_params` で問題ないように見えました

2024-06-26 03:35 UTC, shoynoi commented on app/helpers/application_helper.rb
> +  def admin_edit_other_user(user)
細かいですが、boolを返すので末尾に `?` があると良さそうです

また、scaffoldした時などにリソースのhelperが作成されていたと思いますが、helperはグローバルに定義されてしまうため衝突などに気をつける必要がある点については覚えておいてもらえるといいかと思います！

2024-06-26 04:40 UTC, maru3460 commented on app/controllers/users_controller.rb
> +    if admin_edit_other_user(@user) ? @user.update_without_password(user_params_without_password) : @user.update(user_params)
ヘルパーがviewで使うためのものだと知らなかったです💦
修正します！

2024-06-26 05:43 UTC, hikarook94 approved these changes
LGTM！

2024-06-26 05:43 UTC, merged